 - name: Alta nuevo server
 #  hosts: misservers
 #  remote_user: ansibleuser
 #  become: true   

   tasks:
     - name: Actualizar lista de paquetes
       apt: update_cache=yes
       when: ansible_distribution=="Debian" or ansible_distribution=="Ubuntu"
     - name: Instalar paquetes en Debian y Ubuntu
       when: ansible_distribution=="Debian" or ansible_distribution=="Ubuntu"
       apt:
         name:
           - vim
           - zip
           - net-tools
         state: latest

     - name: Instalar paquetes en Centos-Rocky Linux
       when: ansible_distribution=="Rocky" or ansible_distribution=="Centos"
       yum:
         name:
         - vim
         - zip
         - net-tools
         state: latest
